# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(null=True)),
                ('question_type', models.CharField(choices=[('QCM', 'QCM'), ('OPE', 'Open')], default='QCM', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse_OPEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse_QCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Seance'),
        ),
    ]
