# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_etudiant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(null=True)),
                ('question_type', models.CharField(choices=[('QCM', 'QCM'), ('OPE', 'Open')], default='QCM', max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse_OPEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('id_etudiant', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse_QCM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.PositiveSmallIntegerField()),
                ('id_etudiant', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Seance'),
        ),
        migrations.AddField(
            model_name='lost',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Seance'),
        ),
    ]
