# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('quesion_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='seance',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Seance'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Question'),
        ),
    ]
