# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse_open',
            name='id_etudiant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse_qcm',
            name='id_etudiant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
