# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0002_auto_20160428_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_etudiant', models.IntegerField()),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.Seance')),
            ],
        ),
    ]
