# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0002_auto_20160422_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='commentaire',
            field=models.TextField(null=True),
        ),
    ]
