# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0003_question_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesion_id',
            new_name='question_id',
        ),
    ]
