# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0003_lost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='date',
        ),
    ]
