# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0004_auto_20160426_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('QCM', 'QCM'), ('OPE', 'Open')], default='QCM', max_length=3),
        ),
    ]
