# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0005_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='code',
            new_name='seance',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
